// ===========================================================
// FlixFlex - Central Icon Module
//
// The whole app imports icons from here instead of directly from
// an icon library. Icons come from @tabler/icons-react but keep the
// established names (ArrowRight, Home, ...) so JSX usages are
// unchanged. To swap icon libraries later, edit ONLY this file.
//
// Mapping is generated against the installed package; multiple names
// may alias the same Tabler icon (e.g. Image/ImageIcon -> IconPhoto).
// ===========================================================

// Icon component type (replaces the old `LucideIcon` type).
export type { TablerIcon as LucideIcon } from "@tabler/icons-react"

export {
  IconActivity as Activity,
  IconAlertCircle as AlertCircle,
  IconAlertTriangle as AlertTriangle,
  IconAlignLeft as AlignLeft,
  IconArrowDownRight as ArrowDownRight,
  IconArrowLeft as ArrowLeft,
  IconArrowRight as ArrowRight,
  IconArrowUp as ArrowUp,
  IconArrowsUpDown as ArrowUpDown,
  IconArrowUpRight as ArrowUpRight,
  IconChartBar as BarChart2,
  IconChartBar as BarChart3,
  IconBell as Bell,
  IconLayoutDistributeVertical as BetweenVerticalEnd,
  IconBook as BookOpen,
  IconBriefcase as Briefcase,
  IconBriefcase as BriefcaseBusiness,
  IconCalendar as Calendar,
  IconCalendarEvent as CalendarDays,
  IconCamera as Camera,
  IconCheck as Check,
  IconCircleCheck as CheckCircle,
  IconCircleCheck as CheckCircle2,
  IconSquareCheck as CheckSquare,
  IconChevronDown as ChevronDown,
  IconChevronLeft as ChevronLeft,
  IconChevronRight as ChevronRight,
  IconChevronUp as ChevronUp,
  IconMovie as Clapperboard,
  IconClock as Clock,
  IconCode as Code2,
  IconColumns as Columns,
  IconCopy as Copy,
  IconCopyPlus as CopyPlus,
  IconDatabase as Database,
  IconEdit as Edit2,
  IconArrowsMaximize as Expand,
  IconExternalLink as ExternalLink,
  IconEye as Eye,
  IconEyeOff as EyeOff,
  IconFile as File,
  IconFileText as FileText,
  IconMovie as Film,
  IconFilter as Filter,
  IconFingerprint as Fingerprint,
  IconFolder as Folder,
  IconFolderPlus as FolderPlus,
  IconWorld as Globe,
  IconLayoutGrid as Grid2X2,
  IconGripVertical as GripVertical,
  IconServer2 as HardDrive,
  IconHelp as HelpCircle,
  IconHexagon as Hexagon,
  IconHome as Home,
  IconPhoto as Image,
  IconPhoto as ImageIcon,
  IconBrandInstagram as Instagram,
  IconKey as KeyRound,
  IconStack2 as Layers,
  IconLayout as Layout,
  IconLayoutDashboard as LayoutDashboard,
  IconLayoutGrid as LayoutGrid,
  IconBulb as Lightbulb,
  IconLink as Link2,
  IconBrandLinkedin as Linkedin,
  IconList as List,
  IconLoader2 as Loader2,
  IconLock as Lock,
  IconLogout as LogOut,
  IconMail as Mail,
  IconMapPin as MapPin,
  IconMaximize as Maximize2,
  IconSpeakerphone as Megaphone,
  IconMenu2 as Menu,
  IconMessageCircle as MessageCircle,
  IconMessage as MessageSquare,
  IconMinus as Minus,
  IconDeviceDesktop as Monitor,
  IconMoon as Moon,
  IconDots as MoreHorizontal,
  IconNews as Newspaper,
  IconPalette as Palette,
  IconPlayerPause as Pause,
  IconPencil as Pencil,
  IconPencil as PenTool,
  IconPhone as Phone,
  IconPhoneCall as PhoneCall,
  IconPlayerPlay as Play,
  IconPlug as Plug,
  IconPlus as Plus,
  IconQuote as Quote,
  IconArrowForwardUp as Redo2,
  IconRefresh as RefreshCw,
  IconRocket as Rocket,
  IconRotate as RotateCcw,
  IconDeviceFloppy as Save,
  IconScissors as Scissors,
  IconSearch as Search,
  IconSend as Send,
  IconServer as Server,
  IconSettings as Settings,
  IconShape as Shapes,
  IconShare as Share2,
  IconShield as Shield,
  IconShieldExclamation as ShieldAlert,
  IconShieldCheck as ShieldCheck,
  IconShoppingCart as ShoppingCart,
  IconDeviceMobile as Smartphone,
  IconSortAscending as SortAsc,
  IconSortDescending as SortDesc,
  IconSparkles as Sparkles,
  IconSquare as Square,
  IconEdit as SquarePen,
  IconStar as Star,
  IconSun as Sun,
  IconDeviceTablet as Tablet,
  IconTag as Tag,
  IconTarget as Target,
  IconTrash as Trash2,
  IconTrendingUp as TrendingUp,
  IconBrandTwitter as Twitter,
  IconTypography as Type,
  IconArrowBackUp as Undo2,
  IconLockOpen as Unlock,
  IconUpload as Upload,
  IconUser as User,
  IconUserCheck as UserCheck,
  IconUsers as Users,
  IconUserX as UserX,
  IconVideo as Video,
  IconVolume as Volume2,
  IconVolumeOff as VolumeX,
  IconWand as Wand2,
  IconTool as Wrench,
  IconX as X,
  IconBrandYoutube as Youtube,
  IconBolt as Zap,
  IconZoomIn as ZoomIn,
  IconPhoto as IconPhotoVideo,
} from "@tabler/icons-react"
